BEGIN;

INSERT INTO public.products (
  product_id,
  product_name,
  short_description,
  long_description,
  brand,
  model_number,
  category,
  subcategory,
  tags,
  color_variant,
  regular_price,
  sale_price,
  cost_price,
  image_url_1,
  image_url_2,
  image_url_3,
  stock,
  rating,
  review_count,
  customizable,
  featured
)
VALUES
('PRD001', 'Floral Birthday Wish', 'Hand-painted watercolor birthday card', 'Hand-painted watercolor card with custom message and pressed flower accents. Perfect for making birthdays extra special!', 'Varnika', 'FBW-2024', 'Cards', 'Birthday', 'birthday watercolor handpainted custom flowers', 'Multi-Color', 250, 250, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/greeting%20card.jpg', NULL, NULL, 20, 5, 12, FALSE, FALSE),
('PRD002', 'Floral Birthday Wish', 'Elegant anniversary card with gold foil', 'Elegant anniversary card design with gold foil details and romantic touches', 'Varnika', 'GA-2024', 'Cards', 'Anniversary', 'anniversary gold foil romantic elegant', 'Gold', 300, 300, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 15, 5, 8, FALSE, FALSE),
('PRD003', 'Grateful Hearts', 'Thank you card with pressed flowers', 'Elegant thank you card with pressed flowers and hand-lettered gratitude message', 'Varnika', 'GH-2024', 'Cards', 'Thank You', 'thankyou gratitude flowers handlettered', 'Floral', 250, 250, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/thankyou%20card.jpg', NULL, NULL, 25, 5, 10, FALSE, FALSE),
('PRD004', 'Custom Greeting Card', 'Personalized watercolor greeting card', 'Personalized greeting card with watercolor floral design', 'Varnika', 'CGC-2024', 'Cards', 'Greeting', 'greeting custom watercolor floral personalized', 'Multi-Color', 280, 280, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/wbc.jpg', NULL, NULL, 30, 5, 15, FALSE, FALSE),
('PRD005', 'embroidery art', 'Hand-stitched wildflowers in 6" hoop', 'Hand-stitched wildflowers in 6" hoop. Each petal crafted with French knots and love!', 'Varnika', 'MD-2024', 'Embroidery', 'Hoop Art', 'embroidery wildflowers hoop handstitched french-knots', 'Multi-Color', 800, 800, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/kerchiefpainting.jpg', NULL, NULL, 8, 5, 18, FALSE, FALSE),
('PRD006', 'Vintage Rose', 'Delicate rose embroidery with silk threads', 'Delicate rose embroidery with silk threads and pearl accents', 'Varnika', 'VR-2024', 'Embroidery', 'Hoop Art', 'embroidery rose silk pearls vintage delicate', 'Pink', 850, 850, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 6, 5, 14, FALSE, FALSE),
('PRD007', 'Thread Bangles', 'Handcrafted thread bangles with embroidery', 'Beautiful handcrafted thread bangles with intricate embroidery work', 'Varnika', 'TB-2024', 'Embroidery', 'Accessories', 'bangles thread handcrafted embroidery jewelry', 'Multi-Color', 400, 400, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/bangles.jpg', NULL, NULL, 30, 4.8, 22, FALSE, FALSE),
('PRD008', 'Handmade Bracelets', 'Handcrafted bracelets with embroidery patterns', 'Beautiful handcrafted bracelets with unique embroidery patterns', 'Varnika', 'HB-2024', 'Embroidery', 'Accessories', 'bracelets handmade embroidery jewelry unique', 'Multi-Color', 350, 350, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/bracelets .jpg', NULL, NULL, 25, 4.9, 16, FALSE, FALSE),
('PRD009', 'Embroidery Bow', 'Delicate embroidered bow with vibrant colors', 'Delicate embroidered bow with intricate details and vibrant colors', 'Varnika', 'EB-2024', 'Embroidery', 'Accessories', 'bow embroidery delicate vibrant colorful', 'Multi-Color', 200, 200, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/bow.jpg', NULL, NULL, 40, 4.7, 11, FALSE, FALSE),
('PRD010', 'Wildflower Meadow', 'Hand-stitched wildflowers in 6-inch hoop', 'Delicate hand-stitched wildflowers in a 6-inch wooden hoop. Each petal crafted with French knots', 'Varnika', 'WM-2024', 'Embroidery', 'Hoop Art', 'embroidery wildflowers hoop handstitched wooden french-knots', 'Multi-Color', 800, 800, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/hoopart.jpg', NULL, NULL, 5, 5, 9, FALSE, FALSE),
('PRD011', 'Cosmic Flowers', 'Sparkling resin keychain with real flowers', 'Sparkling resin keychain with real flowers and holographic sparkles. A universe in your pocket!', 'Varnika', 'CF-2024', 'Resin', 'Keychains', 'resin keychain flowers holographic sparkles cosmic', 'Multi-Color', 350, 350, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 20, 4.9, 25, FALSE, FALSE),
('PRD012', 'Ocean Waves Bookmark', 'Colorful resin bookmarks ocean-inspired', 'Colorful resin bookmarks with unique ocean-inspired designs', 'Varnika', 'OWB-2024', 'Resin', 'Bookmarks', 'bookmark resin ocean waves colorful unique', 'Blue', 180, 180, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/bookmark.jpg', NULL, NULL, 35, 4.8, 19, FALSE, FALSE),
('PRD013', 'Cosmic Dreams Pendant', 'Sparkling resin pendant with dried flowers', 'Sparkling resin pendant with dried flowers holographic glitter and gold flakes', 'Varnika', 'CDP-2024', 'Resin', 'Jewelry', 'pendant resin flowers holographic gold jewelry', 'Multi-Color', 350, 350, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/galaxykeychains.jpg', NULL, NULL, 15, 5, 17, FALSE, FALSE),
('PRD014', 'Calligraphy Name Art', 'Watercolor portrait with elegant calligraphy', 'Watercolor portrait from your photo with elegant calligraphy. Soft romantic colors that capture beautiful moments!', 'Varnika', 'CNA-2024', 'Paintings', 'Portrait', 'calligraphy watercolor portrait custom name art romantic', 'Multi-Color', 260000, 900, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/nc.jpg', NULL, NULL, 10, 5, 13, FALSE, FALSE),
('PRD015', 'Dream Catcher', 'Dreamy sunset landscape with custom quote', 'Dreamy sunset landscape painting with custom quote', 'Varnika', 'DC-2024', 'Paintings', 'Landscape', 'dreamcatcher sunset landscape painting custom quote', 'Orange', 1200, 1200, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 5, 5, 7, FALSE, FALSE),
('PRD016', 'Custom Portrait', 'Watercolor couple portrait from photo', 'Watercolor couple portrait from your favorite photo with soft romantic colors', 'Varnika', 'CP-2024', 'Paintings', 'Portrait', 'portrait watercolor couple custom photo romantic', 'Multi-Color', 900, 900, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/potrait.jpg', NULL, NULL, 8, 5, 11, FALSE, FALSE),
('PRD017', 'Resin Art Frame', 'Unique resin art with abstract designs', 'Unique resin art with abstract designs in elegant frame', 'Varnika', 'RAF-2024', 'Frames', 'Resin Art', 'frame resin abstract art elegant unique', 'Multi-Color', 850, 850, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/rart.jpeg', NULL, NULL, 7, 4.9, 6, FALSE, FALSE),
('PRD018', 'Pressed Flower Frame', 'Photo frame with pressed flowers and gold accents', 'Handcrafted photo frame decorated with real pressed flowers and delicate gold accents. Memories made beautiful!', 'Varnika', 'PFF-2024', 'Frames', 'Photo Frame', 'frame pressed-flowers photo gold handcrafted memories', 'Gold', 650, 650, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 12, 4.8, 14, FALSE, FALSE),
('PRD019', 'Resin Photo Frame', 'Beautiful resin frames with unique designs', 'Beautiful resin frames with unique designs and patterns', 'Varnika', 'RPF-2024', 'Frames', 'Photo Frame', 'frame resin photo unique designs patterns', 'Multi-Color', 700, 700, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/resinframes.jpg', NULL, NULL, 15, 4.7, 10, FALSE, FALSE),
('PRD020', 'Celebration Bundle', 'Curated gift box for special occasions', 'Curated gift box with card keychain and mini art piece. Perfect for special occasions and celebrations!', 'Varnika', 'CB-2024', 'Hampers', 'Gift Box', 'hamper gift-box celebration bundle curated special-occasion', 'Multi-Color', 1200, 1200, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/gifthamper.jpg', NULL, NULL, 10, 5, 20, FALSE, FALSE),
('PRD021', 'Couple Matching Set', 'Matching keychains or accessories for couples', 'Matching keychains or accessories for couples', 'Varnika', 'CMS-2024', 'Resin', 'Keychains', 'couple matching keychains accessories set romantic', 'Multi-Color', 500, 500, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/couplematch.jpg', NULL, NULL, 12, 4.9, 8, FALSE, FALSE),
('PRD022', 'Handmade Wedding Card', 'Elegant wedding card with intricate designs', 'Elegant wedding card with intricate designs', 'Varnika', 'HWC-2024', 'Cards', 'Wedding', 'wedding card handmade elegant intricate designs', 'White', 400, 400, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 18, 5, 5, FALSE, FALSE),
('PRD023', 'Custom Embroidered Name Art', 'Hand-stitched floral name embroidery on kerchief', 'Beautiful hand-embroidered name art featuring vibrant red roses, dark green leaves, and elegant black thread lettering. Crafted on premium fabric, this customized hoop art makes a perfect personalized gift for birthdays, anniversaries, or special occasions.', 'Varnika', '', 'Embroidery', 'Hoop Art', 'custom embroidery name art floral handstitched red roses personalized gift handmade', 'Red, Dark Green & Black', 800, 500, 200, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 15, 5, 10, FALSE, FALSE),
('PRD024', 'Sanju name Art', 'Hand-drawn pencil sketch name art', 'Elegant hand-drawn pencil sketch featuring customized name with crown, floral and butterfly detailing. Designed in classic monochrome style, perfect for personalized gifts and wall decor.', 'Varnika', '', 'Name Art', 'Pencil sketch', 'custom name art pencil sketch crown butterfly floral handmade', 'Black & Grey (Monochrome)', 100, 50, 30, 'https://drive.google.com/file/d/1zNY0aqo0OpSR8mxW_bgnogJqkHKJoKVi/view?usp=sharing', NULL, NULL, 15, 5, 11, FALSE, FALSE),
('PRD025', 'Floral Birthday Wish', 'Hand-painted watercolor birthday card', 'Hand-painted watercolor card with custom message and pressed flower accents. Perfect for making birthdays extra special!', 'Varnika', 'FBW-2024', 'Cards', 'Birthday', 'birthday watercolor handpainted custom flowers', 'Multi-Color', 250, 250, 325, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 20, 5, 12, FALSE, FALSE),
('PRD026', 'Minimal Sketch Card', 'Black & white artistic greeting card', 'Elegant hand-drawn minimal sketch greeting card in classic monochrome style. Ideal for modern gifting.', 'Varnika', 'MSC-2024', 'Cards', 'All Occasion', 'minimal sketch black white handmade greeting', 'Black & White', 200, 180, 120, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 25, 5, 8, FALSE, FALSE),
('PRD027', 'Royal Red Celebration Card', 'Traditional red and gold festive card', 'Luxury handmade festive card featuring rich red tones with golden highlights for special celebrations.', 'Varnika', 'RRC-2024', 'Cards', 'Festive', 'red gold festive handmade premium card', 'Red & Gold', 300, 280, 180, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 18, 5, 15, FALSE, FALSE),
('PRD028', 'Maroon Floral Card', 'Elegant maroon floral greeting card', 'Beautiful maroon themed floral card with delicate detailing, perfect for heartfelt messages.', 'Varnika', 'MFC-2024', 'Cards', 'Birthday', 'maroon floral elegant greeting card', 'Maroon', 260, 240, 150, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 22, 4.9, 9, FALSE, FALSE),
('PRD029', 'Custom Embroidered Name Art', 'Hand-stitched floral name embroidery', 'Hand-embroidered name art featuring vibrant red roses and elegant lettering. A perfect personalized decor piece.', 'Varnika', 'CEN-2024', 'Embroidery', 'Hoop Art', 'custom embroidery name floral handmade', 'Red, Dark Green & Black', 800, 750, 500, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 15, 5, 10, FALSE, FALSE),
('PRD030', 'Blue Blossom Card', 'Soft blue floral greeting card', 'Charming handmade card with soft blue and white floral watercolor design.', 'Varnika', 'BBC-2024', 'Cards', 'Birthday', 'blue white floral handmade watercolor', 'Blue & White', 250, 230, 140, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 20, 4.8, 6, FALSE, FALSE),
('PRD031', 'Love Bloom Card', 'White and red romantic greeting card', 'Romantic handmade card with red floral accents on white base, ideal for anniversaries.', 'Varnika', 'LBC-2024', 'Cards', 'Anniversary', 'romantic red white handmade love card', 'White & Red', 270, 250, 160, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 19, 5, 11, FALSE, FALSE),
('PRD032', 'Golden Glow Card', 'Warm yellow festive greeting card', 'Bright yellow handmade greeting card symbolizing positivity and happiness.', 'Varnika', 'GGC-2024', 'Cards', 'Festive', 'yellow golden glow handmade festive card', 'Warm Yellow (Golden Glow)', 280, 260, 170, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 17, 4.9, 7, FALSE, FALSE),
('PRD033', 'Purple Grace Card', 'Elegant purple floral greeting card', 'Graceful purple themed handmade card with delicate floral artwork.', 'Varnika', 'PGC-2024', 'Cards', 'Birthday', 'purple floral elegant handmade greeting', 'Purple', 260, 240, 150, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 16, 5, 5, FALSE, FALSE),
('PRD034', 'Classic Monochrome Art Card', 'Black & white artistic card', 'Stylish monochrome handmade art card suitable for any modern occasion.', 'Varnika', 'CMA-2024', 'Cards', 'All Occasion', 'black white art minimal greeting card', 'Black & White', 220, 200, 130, 'https://raw.githubusercontent.com/Harshavardhani-668/pic/main/anniversary%20love%20card.jpg', NULL, NULL, 21, 4.8, 4, FALSE, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  product_name = EXCLUDED.product_name,
  short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description,
  brand = EXCLUDED.brand,
  model_number = EXCLUDED.model_number,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  tags = EXCLUDED.tags,
  color_variant = EXCLUDED.color_variant,
  regular_price = EXCLUDED.regular_price,
  sale_price = EXCLUDED.sale_price,
  cost_price = EXCLUDED.cost_price,
  image_url_1 = EXCLUDED.image_url_1,
  image_url_2 = EXCLUDED.image_url_2,
  image_url_3 = EXCLUDED.image_url_3,
  stock = EXCLUDED.stock,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  customizable = EXCLUDED.customizable,
  featured = EXCLUDED.featured,
  updated_at = NOW();

COMMIT;
